"""Runtime UI/category patch for procurement menu groups.

Keeps the legacy server implementation intact while aligning navigation and
shopping filters with the production detail-item-code collector.
"""

LED_ITEMS = [
    ("LED다운라이트", "3911151502"),
    ("LED가로등기구", "3911160302"),
    ("LED터널등기구", "3911160304"),
    ("LED경관조명기구", "3911160501"),
    ("LED보안등기구", "3911160802"),
    ("LED투광등기구", "3911161102"),
    ("LED실내조명등", "3911210201"),
]
SOLAR_PANEL_ITEMS = [
    ("태양광발전장치", "2611160701"),
    ("분전반", "3912110101"),
]
POLE_ITEMS = [
    ("스테인리스가로등주", "3911152602"),
    ("가로등주부속자재", "3911152607"),
    ("철제가로등주", "3911152601"),
]
GROUPS = {
    "led": ("LED 조명 조달내역", LED_ITEMS),
    "solar": ("태양광/분전함 조달내역", SOLAR_PANEL_ITEMS),
    "pole": ("등주 조달내역", POLE_ITEMS),
}


def apply_patch():
    import server as s

    label_to_code = {}
    group_labels = {}
    for group, (title, rows) in GROUPS.items():
        labels = []
        for name, code in rows:
            label = f"{name} {code}"
            labels.append(label)
            label_to_code[label] = code
            label_to_code[name] = code
            label_to_code[code] = code
        group_labels[group] = labels

    # Navigation: split procurement data into three code-based sections.
    s.NAVS = [
        ('대시보드','/dashboard'),
        ('LED 조명 조달내역','/g2b/shopping/prdct_detail.php?group=led'),
        ('태양광/분전함 조달내역','/g2b/shopping/prdct_detail.php?group=solar'),
        ('등주 조달내역','/g2b/shopping/prdct_detail.php?group=pole'),
        ('용역현황','/services'),('업체별수주조회','/vendors'),
        ('시장예측','/market'),('순위조회','/ranking'),
        ('매출현황','/sales'),('우리제품','/products'),
        ('입찰','/bids'),('예산','/budgets'),('연차관리','/annual')
    ]

    original_build = s.build_shop_params
    original_where = s.where_shop
    original_shopping = s.shopping_html

    def build_shop_params(qs):
        p = original_build(qs)
        group = (qs.get('group') or ['led'])[0]
        if group not in GROUPS:
            group = 'led'
        p['group'] = group
        # If the user did not explicitly choose checkboxes, select the entire
        # current category by default.
        if 'item' not in qs:
            p['items'] = list(group_labels[group])
        return p

    def where_shop(start, end, region='', q='', items=None, vendor=''):
        # Build the common conditions ourselves so selected UI labels are
        # resolved to detail_item_no, not detail_item_name.
        c = ['base_date BETWEEN ? AND ?']
        v = [start, end]
        if region:
            c.append('demand_region=?')
            v.append(region)
        if q:
            like = f'%{q}%'
            c.append('(vendor_name LIKE ? OR demand_org LIKE ? OR top_org LIKE ? OR contract_name LIKE ? OR item_id LIKE ? OR item_name LIKE ? OR model_name LIKE ? OR detail_item_no LIKE ?)')
            v += [like] * 8
        if items:
            codes = []
            for item in items:
                code = label_to_code.get(str(item), str(item))
                if code and code not in codes:
                    codes.append(code)
            if codes:
                c.append('detail_item_no IN (%s)' % ','.join('?' for _ in codes))
                v += codes
        if vendor:
            if isinstance(vendor, (list, tuple, set)):
                names = [str(x) for x in vendor if str(x)]
                if names:
                    c.append('vendor_name IN (%s)' % ','.join('?' for _ in names))
                    v += names
            else:
                c.append('vendor_name=?')
                v.append(vendor)
        return ' AND '.join(c), v

    def shopping_html(p):
        group = p.get('group', 'led')
        title, _ = GROUPS.get(group, GROUPS['led'])
        old_items = s.DETAIL_ITEMS
        try:
            s.DETAIL_ITEMS = list(group_labels[group])
            html = original_shopping(p)
        finally:
            s.DETAIL_ITEMS = old_items

        # Preserve group on tabs/search/export links generated by the legacy UI.
        html = html.replace('쇼핑몰 세부품 계약내역', title, 1)
        html = html.replace('<input type="hidden" name="view"', f'<input type="hidden" name="group" value="{group}"><input type="hidden" name="view"', 1)
        html = html.replace('조명 조달내역', title)
        # Add group to links that return to the shopping route when absent.
        needle = '/g2b/shopping/prdct_detail.php?'
        html = html.replace(needle, needle + f'group={group}&')
        return html

    s.build_shop_params = build_shop_params
    s.where_shop = where_shop
    s.shopping_html = shopping_html
    return True
